matrix:
  include:
    - language: node_js
      node_js: "12"
      cashe:
        - yarn: true
      before_install:
        - cd stockin 
      install:
        - yarn install
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false
    - language: python
      python: "3.7"
      cache:
        - pip: true
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - pylint **/*.y --load-plugins pylint_django
        - coverage run --source='.' manage.py test
        - coverage xml
