matrix:
  include:
    - language: node_js
      git:
        depth: false
      node_js: 12
      python: 3.7
      dist: xenial
      services:
        - mysql
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "SOht2UWTQXLvdthwP9OYOe8cXn12Z6hSk6TLrhjyUYq2EbRzayTWDe2URL/yhik/h27thifUBpokwIyz7HlTA1Vi3aHUEMYqPREpx7yeiDY84FCm86n2PpkuwDfZTu6EtjxSaHXr9J0xAEyfxj4r4KTbe2mCSFrClTfFCgFFH67oHlh0IsIYoOp7qLQ5hyyKUiHGpulecqKFH21NVxPjAEA/EKuPxaFsLkRc+IAFt/KEaMZVjcWEpdl2XggT/FKKtH/Ev2vwuD4wnSThk8OcwiwNGWUGqNmsfp9rsbgDY8a3vm33SCXrg6/bzsPwkX6RuXUqBDNjLbj84UBpXHf1snr0LK+qe9hI4cgX3O4PbbiAazjJnFcoR3VukWu8k6FfsX+oesRz44i1JcNzfrDdkbA0QBYzd58Tq1C3DATyNdz3XiWIU2b5dKo6LXtaj5K7uL4WcLMGTJST7Q+3nBSNtWxgsNlwM637fn2emQLmJBfBgAFoBZkejXOjSbxg1JwTKHtSG2NHaIWNpfUgszQuCpz69FuHLqoYGcJotf/XQ18hDyPgwMjX3wjOTyzKMQSybZIvjJQyFpA7as97pwfLDqIElynm1uAeZJf6gYdEBqPO0dQT6cgwqD2NPYKgBZq/NiIM6BfNouqxSwhCc4XrWQPZnZt5cX8kJneDWP1nnwg="
      before_install:
      install:
        - cd stockin/frontend
        - yarn install
        - cd ../backend
        - pip3 install -r requirements.txt
      script:
        - python manage.py makemigrations core
        - python manage.py migrate
        - coverage run --source='.' manage.py test
        - coverage report --fail-under=80 -m
        - coverage xml
        - pylint **/*.py --load-plugins pylint_django
        - cd ../frontend
        - yarn test --coverage --watchAll=false
        - ./node_modules/.bin/eslint src
        - yarn coveralls
        - cd ../..
        - sonar-scanner
      after_success:
        - cd stockin/backend
        - coveralls
